library(caret)
data1 <- read.csv("C:/Users/607138/Downloads/HRDataset_v13.csv")
data1$minority.status <- ifelse(data1$RaceDesc == "White" & data1$Sex == "M ","0","1")
data1$minority.status <- as.numeric(data1$minority.status)
data1$online.source <- ifelse(data1$RecruitmentSource == "Careerbuilder" | data1$RecruitmentSource == "Company Intranet - Partner" | data1$RecruitmentSource == "Glassdoor" | data1$RecruitmentSource == "Indeed" | data1$RecruitmentSource == "Internet Search" | data1$RecruitmentSource == "Monster.com" | data1$RecruitmentSource == "On-line Web application" | data1$RecruitmentSource == "Pay Per Click" | data1$RecruitmentSource == "Pay Per Click - Google" | data1$RecruitmentSource == "Search Engine - Google Bing Yahoo" | data1$RecruitmentSource == "Social Networks - Facebook Twitter etc" | data1$RecruitmentSource == "Website Banner Ads","1","0")
set.seed(1)
train.index <- sample(c(1:310), 155)
traindata <- data1[train.index,]
testdata <- data1[-train.index,]
testdata$minority.status <- factor(testdata$minority.status)
model1 <- glm(minority.status ~ online.source, data = traindata, family = 'binomial')
testdata$pred <- predict(model1, testdata)
testdata$pred <- cut(testdata$pred, c(-Inf, 1, Inf), labels = c(0,1))
confusionMatrix(testdata$pred, testdata$minority.status)
model2 <- glm(Termd ~ PayRate, data = traindata, family = 'binomial')
testdata$termdpred <- predict(model2, testdata)
testdata$termdpred <- cut(testdata$termdpred, c(-Inf, -.8277, Inf), labels = c(0,1))
testdata$Termd <- factor(testdata$Termd)
confusionMatrix(testdata$termdpred, testdata$Termd)